name: Env
on:
  push:
  workflow_dispatch:
env:
  NODE_ENV: production
  GH_SECRET: 33
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print env build
        run: echo '${{env.GH_SECRET}}'
          echo '${{env.NODE_ENV}}'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print env build
        run: echo '${{env.GH_SECRET}}'
          echo '${{env.NODE_ENV}}'
