name: Test react app
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get repo code
        uses: actions/checkout@v6
      - name: i dep
        run: npm ci
      - name: test
        run: npm run test
